# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [5]:
# Loading the cities csv file created in WeatherPy to a dataframe
city_vacation_df = pd.read_csv('../WeatherPy/output_data/cities.csv')
city_vacation_df = city_vacation_df[['City', 'Lat', 'Lng', 'Max Temp', 'Humidity', 'Cloudiness', 'Wind Speed', 'Country', 'Date']]
city_vacation_df.head()

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,Vaini,-21.20,-175.20,78.96,83,20,5.75,TO,1623967677
1,Nemuro,43.32,145.57,47.98,87,100,6.35,JP,1623967677
2,Maumere,-8.62,122.21,77.99,80,60,4.81,ID,1623967677
3,Vila Velha,-20.33,-40.29,73.35,73,75,8.05,BR,1623967677
4,Tomatlán,19.93,-105.25,89.31,62,93,13.15,MX,1623967678

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [6]:
# Configure gmaps using the api key
gmaps.configure(api_key=g_key)

In [9]:
# Using the latitude and longitude columns as locations and copying to a new dataframe
# Using the humidity column as weight and copying to a new dataframe
locations = city_vacation_df[['Lat', 'Lng']]
humidity = city_vacation_df['Humidity']

In [10]:
# Creating the Heatmap using gmaps for the humidity of the cities
fig = gmaps.figure(zoom_level=2, center=(0,0))

heat_layer = gmaps.heatmap_layer(locations, weights = humidity, dissipating=False, max_intensity=300, point_radius = 5)

fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [11]:
# Creating a new dataframe with max temperature greater than 70 Farenheit and less than 80 Farenheit and 
# with wind speed less than 10 and
# cloudiness equal to 0
# dropping null vales
# Adding a new column Hotel Name
hotel_df = city_vacation_df.loc[(city_vacation_df['Max Temp'] < 80) & (city_vacation_df['Max Temp'] > 70)
                                               & (city_vacation_df['Wind Speed'] < 10) 
                                               & (city_vacation_df['Cloudiness'] == 0)].dropna()
hotel_df['Hotel Name'] = ' '
hotel_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
96,Pārsābād,39.65,47.92,76.03,59,0,1.19,IR,1623967707,
212,Cayenne,4.93,-52.33,79.09,87,0,1.14,GF,1623967747,
365,Turaif,31.67,38.66,71.71,34,0,9.26,SA,1623967792,
367,Karpathos,35.51,27.21,71.02,77,0,9.46,GR,1623967793,
406,Kiryat Gat,31.61,34.76,70.81,76,0,3.51,IL,1623967805,
501,Darnah,32.77,22.64,71.76,66,0,4.65,LY,1623967835,

In [12]:
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

for index, row in hotel_df.iterrows():
    # get lat, lng from hotel df
    lat = row["Lat"]
    lng = row["Lng"]
    
    params["location"] = f"{lat},{lng}"
    
    base_url = 'https://maps.googleapis.com/maps/api/place/nearbysearch/json'
    
    hotel_name = requests.get(base_url, params=params)
    hotel_name = hotel_name.json()
    
    try:
        hotel_df.loc[index, 'Hotel Name'] = hotel_name["results"][0]["name"]
    except:
        print('No hotel found within 5000m in: ' + row['City'])

In [13]:
hotel_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
96,Pārsābād,39.65,47.92,76.03,59,0,1.19,IR,1623967707,Peacock Hotel Magi
212,Cayenne,4.93,-52.33,79.09,87,0,1.14,GF,1623967747,Hôtel Le Dronmi
365,Turaif,31.67,38.66,71.71,34,0,9.26,SA,1623967792,Turaif
367,Karpathos,35.51,27.21,71.02,77,0,9.46,GR,1623967793,Alex
406,Kiryat Gat,31.61,34.76,70.81,76,0,3.51,IL,1623967805,OlusHome
501,Darnah,32.77,22.64,71.76,66,0,4.65,LY,1623967835,زاوية الرفاعي

In [36]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]
display_city = list(hotel_df['City'])

In [39]:
# Add marker layer on top of heat map

hotel_layer = gmaps.marker_layer(locations,
    hover_text= display_city,                            
    info_box_content=hotel_info
)


fig = gmaps.figure(zoom_level=2, center=(0,0))

fig.add_layer(heat_layer)
fig.add_layer(hotel_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))